apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    role: kibana
  ports:
    - name: http
      port: 5601
      protocol: TCP
      targetPort: 5601
      nodePort: 30002
  sessionAffinity: None
  type: NodePort
