apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    role: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     role: kibana
  template:
    metadata:
      labels:
        role: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.3.2
        env:
        - name: CLUSTER_NAME
          value: 32BitBilgisayar
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: http
        volumeMounts:
          - name: config
            mountPath: /usr/share/kibana/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: kibana-config
